apiVersion: apps/v1
kind: Deployment
metadata:
  name: injestion-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: injestion-deployment
  template:
    metadata:
      labels:
        app: injestion-deployment
    spec:
      containers:
      - name: injestion-deployment
        image: acrdevtodoacr.azurecr.io/injestiondev:50feb911077a53114efd04a83dc8d6f2a8638a5f
        ports:
        - containerPort: 8000