apiVersion: apps/v1
kind: Deployment
metadata:
  name: injestion-deployment
spec:
  selector:
    matchLabels:
      app: injestion-deployment
  template:
    metadata:
      labels:
        app: injestion-deployment
    spec:
      containers:
      - name: injestion-deployment
        image: acrdevtodoacr.azurecr.io/injestiondev
        ports:
        - containerPort: 8000
